# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "docker" do |d, override|
    d.image = "smerrill/vagrant-centos"
    d.has_ssh = true

    # This is needed if you have non-Docker provisioners in the Vagrantfile.
    override.vm.box = nil
  end

  config.vm.provider "lxc" do |d, override|
    override.vm.box = "smerrill/centos-7"
  end

  # When using rsync-blitz in your projects, you should wrap these configs in
  # an 'if Vagrant.has_plugin?("vagrant-rsync-blitz")' test.

  # Configure the window for blitz to coalesce writes.
  config.blitz.latency = 1.0
  config.blitz.time_format = "%H:%M:%S"

  # Blitz will run `vagrant rsync-blitz` after the machines in
  # your Vagrant environment start if you set this to true.
  config.blitz.autostart = true

  # Add a multi-box setup.
  config.vm.define "rsync", primary: true do |m|
    m.vm.synced_folder "../files", "/opt/vagrant/rsynced_folder", type: "rsync",
      rsync__exclude: [".git/", ".idea/"]
  end

  config.vm.define "rsync2", primary: true do |m|
    m.vm.synced_folder "../files", "/opt/vagrant/rsynced_folder", type: "rsync",
      rsync__exclude: [".git/", ".idea/"]
  end

  config.vm.define "norsync" do |m|
  end
end
